### ISSUE TITLE
Consider adding to adventure docs

### ISSUE THREAD

**Issue by ryantheleach** [Siroshun09/TranslationLoader#31]
I've not fully investigated your JavaDocs (It would be great to see some examples in the readme) but it seems like TranslationLoader is a missing piece of the puzzle for loading Kyori Adventure translations from files.

Assuming it's production ready, and you wouldn't mind, you may want to get it listed on the adventure documentation. 

https://github.com/KyoriPowered/adventure-docs/pull/50#issuecomment-1024179766

**Comment by Siroshun09** [comment]
Thank you for the issue.

It's nice to hear that, but I don't think TranslationLoader is ready for wide use yet.

First, this library is feature-first, so there are some compromises in the API design.
API needs to be improved to a better design.
Currently, using TranslationLoader requires my [ConfigAPI](https://github.com/Siroshun09/ConfigAPI) to be added as a dependency, which is inconvenient. I am planning to support [Sponge Configurate](https://github.com/SpongePowered/Configurate).

Also, it is not well tested. More tests need to be implemented for enhanced reliability.

In addition, the docs are not enough; there is Javadoc, but I should write implementation examples on GitHub Wiki or README.

For these reasons, I will not now ask for the library to be listed in the Adventure documentation.

Thanks for the suggestion.
